// <auto-generated />
namespace ProjectResort.Context1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Edit11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edit11));
        
        string IMigrationMetadata.Id
        {
            get { return "202402161739241_Edit11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
