// <auto-generated />
namespace ProjectResort.Context1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Refresh2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refresh2));
        
        string IMigrationMetadata.Id
        {
            get { return "202402190808062_Refresh2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
